require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Metrics:
  Enabled: false

Naming:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

RSpec/SpecFilePathFormat:
  CustomTransform:
    OmniCache: omnicache

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
